### ISSUE TITLE
`docker run busybox true` doesn't work in ghcr.io/catthehacker/ubuntu:full-18.04

### ISSUE THREAD

**Issue by jsoref** [catthehacker/virtual-environments-fork#3]
### Description

The runner user isn't a member of the `docker` group, and `/var/run/docker.sock` is `root:root` which means that GitHub Workflows that expect to be able to run docker commands fail.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [X] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```sh
% act --version
act version 0.2.24
% docker images|grep full
ghcr.io/catthehacker/ubuntu       full-18.04       ba48b179cc81   2 months ago   36.9GB
```

### Expected behavior

the docker socket should be accessible by the runner user.

Implementation detail, for GHA, `runner` `gid=docker` and the `docker.sock` group is `docker`.

### Actual behavior

```
runner@docker-desktop:~$ docker run busybox true
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create": dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
```

### Repro steps

1. Get a repository to use w/ act
```sh
git clone https://github.com/jsoref/nebula-python --branch act
cd nebula-python
```

2. Try running w/ act
```sh
act -P ubuntu-18.04=ghcr.io/catthehacker/ubuntu:full-18.04 
# wait a few hours
# eventually this fails with an unhappy message
```

3. Enter act virtual-environment
```sh
docker exec -it $(docker ps|grep cat|perl -pne 's/\s.*//') bash
```

4. Test docker
```sh
docker run busybox true
```

5. Workaround
```sh
sudo chown runner /var/run/docker.sock
```

**Comment by catthehacker** [comment]
https://github.com/nektos/act/issues/724
&
https://github.com/nektos/act/issues/398
